BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.import_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_name text NOT NULL,
  source_checksum text NOT NULL,
  status text NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'completed', 'failed')),
  imported_counts jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  error_message text
);

CREATE TABLE IF NOT EXISTS public.import_rejections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_run_id uuid NOT NULL REFERENCES public.import_runs(id) ON DELETE CASCADE,
  source_table text NOT NULL,
  source_record_id text,
  reason text NOT NULL,
  source_payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (import_run_id, source_table, source_record_id)
);

ALTER TABLE public.branches ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS branches_email_lower_uidx ON public.branches (lower(email));
CREATE INDEX IF NOT EXISTS branches_province_city_idx ON public.branches (province, city);
DROP TRIGGER IF EXISTS branches_set_updated_at ON public.branches;
CREATE TRIGGER branches_set_updated_at BEFORE UPDATE ON public.branches
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.super_admin_profiles (
  auth_user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  legacy_user_id text UNIQUE,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  phone text,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
  avatar text,
  preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_login_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.staff_users (
  id text PRIMARY KEY,
  branch_id text REFERENCES public.branches(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  role text NOT NULL CHECK (role IN ('branch_manager', 'customer')),
  password_hash text NOT NULL,
  password_changed_by_branch boolean NOT NULL DEFAULT false,
  last_password_change timestamptz,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
  avatar text,
  preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_login_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT staff_users_branch_rule CHECK (
    (role = 'branch_manager' AND branch_id IS NOT NULL) OR role = 'customer'
  )
);
CREATE UNIQUE INDEX IF NOT EXISTS staff_users_email_lower_uidx ON public.staff_users (lower(email));
CREATE INDEX IF NOT EXISTS staff_users_phone_idx ON public.staff_users (phone);
CREATE INDEX IF NOT EXISTS staff_users_branch_idx ON public.staff_users (branch_id);
DROP TRIGGER IF EXISTS staff_users_set_updated_at ON public.staff_users;
CREATE TRIGGER staff_users_set_updated_at BEFORE UPDATE ON public.staff_users
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS super_admin_profiles_set_updated_at ON public.super_admin_profiles;
CREATE TRIGGER super_admin_profiles_set_updated_at BEFORE UPDATE ON public.super_admin_profiles
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Do not backfill staff from the legacy Supabase users table: it can contain
-- obsolete branch IDs. The canonical importer loads branches first and then
-- imports the validated users from data/db_store.json.

INSERT INTO public.super_admin_profiles (
  auth_user_id, legacy_user_id, name, email, phone, status, avatar, preferences, created_at
)
SELECT au.id, u.id, u.name, lower(u.email), u.phone, coalesce(u.status,'active'),
  u.avatar, coalesce(u.preferences,'{}'::jsonb), coalesce(u.created_at,now())
FROM public.users u JOIN auth.users au ON lower(au.email)=lower(u.email)
WHERE u.role='super_admin'
ON CONFLICT (auth_user_id) DO UPDATE SET
  legacy_user_id=excluded.legacy_user_id, name=excluded.name, email=excluded.email,
  phone=excluded.phone, status=excluded.status, avatar=excluded.avatar, preferences=excluded.preferences;

COMMENT ON TABLE public.users IS
  'Legacy compatibility table. New Super Admin identities use super_admin_profiles; other accounts use staff_users.';

ALTER TABLE public.shipments
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS sender_print_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS receiver_print_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_printed_role text,
  ADD COLUMN IF NOT EXISTS sticker_print_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sticker_batch_ref text,
  ADD COLUMN IF NOT EXISTS sticker_printed_at timestamptz,
  ADD COLUMN IF NOT EXISTS delivery_issue jsonb,
  ADD COLUMN IF NOT EXISTS remittance_batch_id text,
  ADD COLUMN IF NOT EXISTS remittance_settled_at timestamptz,
  ADD COLUMN IF NOT EXISTS seller_payout_dispute_at timestamptz;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='shipments_origin_branch_fk') THEN
    ALTER TABLE public.shipments ADD CONSTRAINT shipments_origin_branch_fk FOREIGN KEY(origin_branch_id) REFERENCES public.branches(id) ON UPDATE CASCADE ON DELETE RESTRICT NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='shipments_destination_branch_fk') THEN
    ALTER TABLE public.shipments ADD CONSTRAINT shipments_destination_branch_fk FOREIGN KEY(destination_branch_id) REFERENCES public.branches(id) ON UPDATE CASCADE ON DELETE RESTRICT NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='shipments_current_branch_fk') THEN
    ALTER TABLE public.shipments ADD CONSTRAINT shipments_current_branch_fk FOREIGN KEY(current_branch_id) REFERENCES public.branches(id) ON UPDATE CASCADE ON DELETE RESTRICT NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='shipments_status_check') THEN
    ALTER TABLE public.shipments ADD CONSTRAINT shipments_status_check CHECK(status IN ('pre_booked','verified','booked','in_transit','received_at_branch','out_for_delivery','delivered','returned','cancelled')) NOT VALID;
  END IF;
END $$;
-- Branch foreign keys are NOT VALID intentionally. They protect all new/imported
-- rows without making this migration fail on unrelated stale rows already present
-- in Supabase. Validate them after the canonical import and legacy cleanup.
ALTER TABLE public.shipments VALIDATE CONSTRAINT shipments_status_check;
CREATE INDEX IF NOT EXISTS shipments_route_status_idx ON public.shipments(origin_branch_id,destination_branch_id,status);
CREATE INDEX IF NOT EXISTS shipments_customer_user_idx ON public.shipments(customer_user_id) WHERE customer_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS shipments_booked_at_idx ON public.shipments(booked_at DESC);
CREATE INDEX IF NOT EXISTS shipments_sender_gin_idx ON public.shipments USING gin(sender);
CREATE INDEX IF NOT EXISTS shipments_receiver_gin_idx ON public.shipments USING gin(receiver);
DROP TRIGGER IF EXISTS shipments_set_updated_at ON public.shipments;
CREATE TRIGGER shipments_set_updated_at BEFORE UPDATE ON public.shipments
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.shipment_status_events (
  id text PRIMARY KEY,
  shipment_id text NOT NULL REFERENCES public.shipments(id) ON UPDATE CASCADE ON DELETE CASCADE,
  status text NOT NULL,
  location text NOT NULL,
  branch_name text NOT NULL,
  occurred_at timestamptz NOT NULL,
  note text NOT NULL,
  updated_by text NOT NULL,
  driver_name text,
  driver_phone text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS shipment_status_events_timeline_idx ON public.shipment_status_events(shipment_id,occurred_at);

ALTER TABLE public.branch_expenses ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS branch_expenses_branch_date_idx ON public.branch_expenses(branch_id,expense_date DESC);
DROP TRIGGER IF EXISTS branch_expenses_set_updated_at ON public.branch_expenses;
CREATE TRIGGER branch_expenses_set_updated_at BEFORE UPDATE ON public.branch_expenses FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.branch_settlements ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS branch_settlements_status_date_idx ON public.branch_settlements(settlement_status,settled_at DESC);
DROP TRIGGER IF EXISTS branch_settlements_set_updated_at ON public.branch_settlements;
CREATE TRIGGER branch_settlements_set_updated_at BEFORE UPDATE ON public.branch_settlements FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.is_super_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT EXISTS(SELECT 1 FROM public.super_admin_profiles p WHERE p.auth_user_id=auth.uid() AND p.status='active');
$$;
REVOKE ALL ON FUNCTION public.is_super_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_super_admin() TO authenticated;

ALTER TABLE public.super_admin_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branch_settlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.import_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.import_rejections ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS super_admin_read_own_profile ON public.super_admin_profiles;
CREATE POLICY super_admin_read_own_profile ON public.super_admin_profiles FOR SELECT TO authenticated USING(auth_user_id=auth.uid());
DROP POLICY IF EXISTS super_admin_manage_staff ON public.staff_users;
CREATE POLICY super_admin_manage_staff ON public.staff_users FOR ALL TO authenticated USING(public.is_super_admin()) WITH CHECK(public.is_super_admin());
DROP POLICY IF EXISTS super_admin_manage_branches ON public.branches;
CREATE POLICY super_admin_manage_branches ON public.branches FOR ALL TO authenticated USING(public.is_super_admin()) WITH CHECK(public.is_super_admin());
DROP POLICY IF EXISTS super_admin_manage_branch_settlements ON public.branch_settlements;
CREATE POLICY super_admin_manage_branch_settlements ON public.branch_settlements FOR ALL TO authenticated USING(public.is_super_admin()) WITH CHECK(public.is_super_admin());
DROP POLICY IF EXISTS super_admin_read_import_runs ON public.import_runs;
CREATE POLICY super_admin_read_import_runs ON public.import_runs FOR SELECT TO authenticated USING(public.is_super_admin());
DROP POLICY IF EXISTS super_admin_read_import_rejections ON public.import_rejections;
CREATE POLICY super_admin_read_import_rejections ON public.import_rejections FOR SELECT TO authenticated USING(public.is_super_admin());

COMMIT;
